version: '3.8'

services:
  # Redis for queue backend
  redis:
    image: redis:7-alpine
    container_name: dolphin-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  # Dolphin Connector Service
  connector:
    build:
      context: .
      dockerfile: deployments/Dockerfile
    container_name: connector
    ports:
      - "8080:8080"  # API server
      - "9090:9090"  # Metrics
    environment:
      - REDIS_URL=redis://redis:6379
      - MODAL_API_ENDPOINT=https://abhishekgautam011--dolphin-parser-dolphinparser
      - LOG_LEVEL=info
      - PORT=8080
    volumes:
      - ./configs:/app/configs:ro
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Redis monitoring (optional)
  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOSTS=redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  redis-data: