server:
  port: 8080
  max_connections: 100
  read_timeout: 300s
  write_timeout: 300s
  max_request_size: 52428800
  rate_limit_per_client: 20   # Higher limit for testing
  graceful_shutdown_timeout: 10s
  backpressure_threshold: 50   # Lower threshold for testing

queue:
  redis_url: "redis://localhost:6379"
  max_size: 100          # Smaller queue for testing
  ttl: 1h               # Shorter TTL for testing
  queue_key: "dolphin:test:requests"
  processing_key: "dolphin:test:processing"
  max_retry_count: 2
  recovery_interval: 1m

batch_formation:
  max_batch_size: 8      # Smaller batches for testing
  min_batch_size: 1
  check_interval: 100ms  # More frequent checks

modal:
  base_url: "https://abhishekgautam011--dolphin-parser-dolphinparser"
  timeout: 60s
  max_retries: 2
  retry_delay: 1s
  max_concurrent_batches: 2
  circuit_breaker:
    failure_threshold: 3
    cooldown_period: 10s
    health_check_interval: 5s
  connection_pool:
    max_idle_connections: 5
    idle_connection_timeout: 30s

response:
  timeout: 5m
  cleanup_interval: 1m

monitoring:
  enable_metrics: true
  prometheus_port: 9090
  log_level: "debug"