server:
  port: 8199

batch_formation:
  max_batch_size: 32
  check_interval: 10s

modal:
  base_url: "https://abhishekgautam011--dolphin-parser-dolphinparser"
  timeout: 600s
  max_retries: 0
  retry_delay: 0s